version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: /myapp/dockerhub-username
    DOCKERHUB_PASSWORD: /myapp/dockerhub-password
    DOCKERHUB_REPO: /myapp/dockerhub-repo
    AWS_REGION: /myapp/aws-region

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install awscli --upgrade

  pre_build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Setting IMAGE_TAG..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $DOCKERHUB_REPO:latest .
      - docker tag $DOCKERHUB_REPO:latest $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to Docker Hub..."
      - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG
      - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest

      - echo "Creating imagedefinitions.json for CodeDeploy..."
      - printf '[{"name":"container-name","imageUri":"%s/%s:%s"}]' \
          $DOCKERHUB_USERNAME $DOCKERHUB_REPO $IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
